Structure VIR-level identifiers with an explicit disambiguator, and rename rust-provided disambiguators in a stable manner
verus-lang/verus pull request #1003
Opened 2024-02-20 23:09 UTC by utaal-b

As discussed for https://github.com/verus-lang/verus/pull/994.

2024-02-21 18:46 UTC, utaal-b commented on source/rust_verify/src/singular.rs
> +            res.push_str("____");
This is probably not quite right yet. I'll come back to it in a bit.

2024-02-26 18:35 UTC, tjhance requested changes
Can we remove the suffixes and fold the functionality into the disambiguator? It would be nice to make VarIdentDisambiguate a small Copy type and remove the extra Arc.

2024-02-26 18:35 UTC, tjhance commented on source/vir/src/def.rs
> +        VarIdentDisambiguate::RustcId(id) | VarIdentDisambiguate::ClosureReturnValue(id) => {
why do multiple cases go to the same body?

2024-02-26 18:35 UTC, tjhance commented on source/vir/src/def.rs
> +        }
Same question

2024-02-26 18:37 UTC, tjhance commented on source/vir/src/def.rs
> +    x.push_suffix(&format!("{SUBST_RENAME_SEPARATOR}{n}"))
I don't think this is necessary. `subst_rename_binders` already checks that the new subst index won't trample any existing 'free_vars'. And I don't see why nesting the idents would help anyway.

2024-02-27 00:49 UTC, Chris-Hawblitzel commented
Ok, I think the last few commits should address the comments so far.

2024-02-27 17:21 UTC, tjhance approved these changes

2024-02-27 18:08 UTC, merged